//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPIForCRUD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblItemMaster
    {
        public int Item_ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<byte> Isactive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public string CreatedOn { get; set; }
        public Nullable<System.DateTime> CreatedByIP { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string UpdatedByIP { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public string DeletedByIP { get; set; }
    }
}
